---
- name: Create CA
  hosts: ca

#  vars:
#    secret_ca_passphrase: "Th3!PassW0rD" # (required)
#    ca_path: "/certificates"             # (optional) - default is /certificates
#    ca_certname: "ca-certificate"        # (optional) - default is ca-certificate
#    ca_common_name: "Ansible CA"         # (optional) - default is "Ansible CA"
#    country_name: "CZ"                   # (optional) - default is "CZ"
#    state_or_province_name: "Brno"       # (optional) - default is "Brno"
#    locality_name: "Brno"                # (optional) - default is "Brno"
#    organization_name: "Red Hat"         # (optional) - default is "Red Hat"
#    organizational_unit_name: "Ansible"  # (optional) - default is "Ansible"

  tasks:
    - name: Check we have all variables configured
      ansible.builtin.assert:
        that:
          - secret_ca_passphrase is defined
        fail_msg: "Failed: Variable secret_ca_passphrase is not set."
    
    - name: Make sure folder for CA exists
      ansible.builtin.file:
        path: "{{ ca_path | default('/certificates') }}"
        state: directory
        mode: 0700
        owner: root
        group: root

    - name: Make sure python3-cryptography package is installed
      ansible.builtin.dnf:
        name: python3-cryptography
        state: latest        

    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        path: "{{ ca_path | default('/certificates') }}/{{ ca_certname | default('ca-certificate') }}.key"
        cipher: auto
        passphrase: "{{ secret_ca_passphrase }}"

    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ca_path | default('/certificates') }}/{{ ca_certname | default('ca-certificate') }}.key"
        privatekey_passphrase: "{{ secret_ca_passphrase }}"
        common_name: "{{ ca_common_name | default('Ansible CA') }}"
        country_name: "{{ country_name | default('CZ') }}"
        state_or_province_name: "{{ state_or_province_name | default('Brno') }}"
        locality_name: "{{ locality_name | default('Brno') }}"
        organization_name: "{{ organization_name | default('Red Hat') }}"
        organizational_unit_name: "{{ organizational_unit_name | default('Ansible') }}"
        use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: yes
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr

    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ ca_path | default('/certificates') }}/{{ ca_certname | default('ca-certificate') }}.pem"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "{{ ca_path | default('/certificates') }}/{{ ca_certname | default('ca-certificate') }}.key"
        privatekey_passphrase: "{{ secret_ca_passphrase }}"
        provider: selfsigned
